### ISSUE TITLE
Provide a default implementation of the Probe

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#420]
Currently all of the instrumentation provides their own implementations of the `Probe` interface. There is a lot of repeated, mostly untested, code shared across all of these implementations.

Instead, provide a base implementation for instrumentation to use. This will use the instrumentation manifest (#419) to construct a tail made `Probe`.

The `Manager` will continue to work with `Probe`s. This means it will still be possible for new instrumentation that is really different to provide their own. Or they can just wrap the default and override a method or two.

### TODO

- [x] PoC draft showing full change (likely too large to be submitted for a single PR): https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/451
- [x] PR base implementation: https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/452
- [x] PR refactor gRPC server use of base implementation: #477 
- [x] PR refactor gRPC client use of base implementation: #478
- [x] PR refactor net/http server use of base implementation: #479
- [x] PR refactor net/http client use of base implementation: #480
- [x] PR refactor the gin use of base implementation: #481
- [x] PR refactor database/sql use of base implementation: #482
